# Generated by Django 5.2.11 on 2026-02-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_method',
            field=models.CharField(choices=[('OTP', 'OTP (Time-based)'), ('QR', 'QR Code')], default='OTP', max_length=20),
        ),
    ]
