# Generated by Django 6.0.3 on 2026-03-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_activation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='functions',
            field=models.CharField(blank=True, default='', help_text="Titre du poste / rôle au sein de l'organisation.", max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Devient True après l'activation OTP/QR. Contrôle la capacité de connexion."),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text="Administrateur au niveau de la plateforme. Distinct des rôles de l'organisation."),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, default='', help_text="Secret TOTP pour les applications d'authentification.", max_length=64),
        ),
    ]
