# Generated by Django 5.2.11 on 2026-02-24 17:19

import django.utils.timezone
import src.common.types
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ORG_ADMIN', 'ORG_ADMIN'), ('ORG_MEMBER', 'ORG_MEMBER'), ('AUDITOR', 'AUDITOR')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('INVITED', 'INVITED'), ('PENDING_ACTIVATION', 'PENDING_ACTIVATION'), ('ACTIVE', 'ACTIVE'), ('DEACTIVATED', 'DEACTIVATED')], db_index=True, default=src.common.types.MembershipStatus['INVITED'], max_length=25)),
                ('invitation_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'memberships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Used in DID URI path.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', help_text='Official organization contact email.', max_length=254)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'PENDING_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('SUSPENDED', 'SUSPENDED')], db_index=True, default=src.common.types.OrgStatus['PENDING_REVIEW'], max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
    ]
