# Generated by Django 6.0.3 on 2026-03-23 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
        ('organizations', '0003_membership_has_audit_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='has_audit_access',
            field=models.BooleanField(default=False, help_text="Accorde à ce membre l'accès aux journaux d'audit. ORG_ADMIN a toujours un accès d'audit indépendamment de cet indicateur."),
        ),
        migrations.AlterField(
            model_name='organization',
            name='authorization_document',
            field=models.ForeignKey(blank=True, help_text="Requis. Preuve administrative pour l'inscription sur la plateforme.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_authorization_docs', to='files.file'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="E-mail de contact officiel de l'organisation.", max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='justification_document',
            field=models.ForeignKey(blank=True, help_text='Optionnel. Document de justification supplémentaire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_justification_docs', to='files.file'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text="Identifiant sécurisé pour les URL. Utilisé dans le chemin de l'URI DID.", max_length=100, unique=True),
        ),
    ]
