# Generated by Django 6.0.4 on 2026-04-28 11:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nom du système client (ex: Port Platform)', max_length=255)),
                ('client_id', models.CharField(help_text='Identifiant unique du client', max_length=100, unique=True)),
                ('client_secret_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'machine_clients',
            },
        ),
    ]
