# Generated by Django 5.2.11 on 2026-02-27 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(help_text='Denormalized — survives user deletion.', max_length=255)),
                ('action', models.CharField(choices=[('ORG_CREATED', 'Organization created'), ('ORG_APPROVED', 'Organization approved'), ('ORG_REJECTED', 'Organization rejected'), ('ORG_SUSPENDED', 'Organization suspended'), ('MEMBER_INVITED', 'Member invited'), ('MEMBER_ACTIVATED', 'Member activated'), ('MEMBER_ROLE_CHANGED', 'Member role changed'), ('MEMBER_DEACTIVATED', 'Member deactivated'), ('CERT_UPLOADED', 'Certificate uploaded'), ('CERT_ROTATED', 'Certificate rotated'), ('CERT_REVOKED', 'Certificate revoked'), ('DOC_CREATED', 'Document created'), ('DOC_SUBMITTED', 'Document submitted for review'), ('DOC_APPROVED', 'Document approved'), ('DOC_REJECTED', 'Document rejected'), ('DOC_SIGNED', 'Document signed'), ('DOC_PUBLISHED', 'Document published'), ('DOC_DEACTIVATED', 'Document deactivated'), ('USER_LOGIN', 'User login'), ('USER_PASSWORD_CHANGED', 'Password changed'), ('USER_PASSWORD_RESET', 'Password reset')], max_length=30)),
                ('resource_type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('MEMBERSHIP', 'Membership'), ('CERTIFICATE', 'Certificate'), ('DID_DOCUMENT', 'DID Document'), ('USER', 'User')], max_length=20)),
                ('resource_id', models.UUIDField(help_text='PK of the affected resource.')),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable summary.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context: old_status→new_status, fingerprint, etc.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_logs_organiz_86ff70_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'), models.Index(fields=['actor', '-created_at'], name='audit_logs_actor_i_3b0e80_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx')],
            },
        ),
    ]
