# Generated by Django 6.0.3 on 2026-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("ORG_CREATED", "Organization created"),
                    ("ORG_APPROVED", "Organization approved"),
                    ("ORG_REJECTED", "Organization rejected"),
                    ("ORG_SUSPENDED", "Organization suspended"),
                    ("MEMBER_INVITED", "Member invited"),
                    ("MEMBER_ACTIVATED", "Member activated"),
                    ("MEMBER_ROLE_CHANGED", "Member role changed"),
                    ("MEMBER_DEACTIVATED", "Member deactivated"),
                    ("CERT_UPLOADED", "Certificate uploaded"),
                    ("CERT_ROTATED", "Certificate rotated"),
                    ("CERT_REVOKED", "Certificate revoked"),
                    ("DOC_CREATED", "Document created"),
                    ("DOC_DRAFT_UPDATED", "Document draft updated"),
                    ("DOC_VM_ADDED", "Verification method added"),
                    ("DOC_VM_REMOVED", "Verification method removed"),
                    ("DOC_SUBMITTED", "Document submitted for review"),
                    ("DOC_APPROVED", "Document approved"),
                    ("DOC_REJECTED", "Document rejected"),
                    ("DOC_SIGNED", "Document signed"),
                    ("DOC_PUBLISHED", "Document published"),
                    ("DOC_DEACTIVATED", "Document deactivated"),
                    ("USER_LOGIN", "User login"),
                    ("USER_LOGOUT", "User logout"),
                    ("USER_ACTIVATED", "User account activated"),
                    ("USER_PASSWORD_CHANGED", "Password changed"),
                    ("USER_PASSWORD_RESET", "Password reset"),
                    ("DID_RESOLVED", "DID document resolved"),
                    ("DID_SEARCHED", "DID search performed"),
                ],
                max_length=30,
            ),
        ),
    ]
