# Generated by Django 6.0.3 on 2026-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(choices=[('ORGANIZATION', 'Organization'), ('MEMBERSHIP', 'Membership'), ('CERTIFICATE', 'Certificate'), ('DID_DOCUMENT', 'DID Document'), ('USER', 'User Account')], max_length=20),
        ),
    ]
