# Generated by Django 6.0.3 on 2026-03-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_alter_auditlog_action_alter_auditlog_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='actor_email',
            field=models.CharField(help_text="Dénormalisé — survit à la suppression de l'utilisateur.", max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Résumé lisible par un humain.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Contexte sup : old_status→new_status, empreinte, etc.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.UUIDField(help_text='PK de la ressource concernée.'),
        ),
    ]
