# Generated by Django 6.0.4 on 2026-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_alter_auditlog_actor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization_name',
            field=models.CharField(blank=True, default='', help_text="Dénormalisé — survit à la suppression de l'organisation.", max_length=255),
        ),
    ]
