# Generated by Django 6.0.4 on 2026-05-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_add_organization_name_to_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.UUIDField(blank=True, help_text='PK de la ressource concernée.', null=True),
        ),
    ]
