server:
  servlet:
    contextPath: /
    mappings:
      properties: "/1.0/properties"
      resolve: "/1.0/identifiers"
      methods: "/1.0/methods"
      testIdentifiers: "/1.0/testIdentifiers"
      traits: "/1.0/traits"
  port: "8080"

spring:
  profiles:
    active: ${uniresolver_web_spring_profiles_active:default}

uniresolver:
  drivers:

    # ── did:web ─────────────────────────────────────────────────────────────
    - pattern: "^(did:web:.+)$"
      url: http://uni-resolver-driver-did-uport:8081/
      testIdentifiers:
        - did:web:identity.foundation
        - did:web:danubetech.com
      traits:
        deactivatable: true
        enumerable: false
        historyAvailable: false
        humanReadable: true
