networks:
  annuaire_staging_net:
    external: true

services:
  ##################################################
  # DIF UNIVERSAL REGISTRAR
  #################################################
  uni-registrar-web:
    image: universalregistrar/uni-registrar-web:latest
    container_name: uni-registrar-web
    restart: unless-stopped
    #ports:
    #  - "9080:9080"
    volumes:
      - ./application-uniregistrar.yml:/opt/universal-registrar/uni-registrar-web/application.yml:ro
    networks:
      - annuaire_staging_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # did:web driver — writes DID docs to the shared volume
  driver-did-web:
    image: universalregistrar/driver-did-web:latest
    container_name: uni-registrar-driver-did-web
    restart: unless-stopped
    environment:
      uniregistrar_driver_did_web_basePath: /app/data/dids
      uniregistrar_driver_did_web_baseUrl: https://annuairedid.qcdigitalhub.com
      #uniregistrar_driver_did_web_generatedFolder: /generated
    volumes:
      - dids_volume:/app/data/dids
    networks:
      - annuaire_staging_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  ############################################
  # DIF UNIVERSAL RESOLVER
  ###########################################
  uni-resolver-web:
    image: universalresolver/uni-resolver-web:latest
    container_name: uni-resolver-web
    restart: unless-stopped
    #ports:
    #  - "8080:8080"
    volumes:
      - ./application-uniresolver.yml:/opt/universal-resolver/uni-resolver-web/application.yml:ro
    networks:
      - annuaire_staging_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # did:web + did:ethr + did:ens + did:peer (uPort/Veramo driver)
  uni-resolver-driver-did-uport:
    image: uport/uni-resolver-driver-did-uport:5.0.3
    container_name: uni-resolver-driver-did-uport
    restart: unless-stopped
    networks:
      - annuaire_staging_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  dids_volume:
    external: true
