# Generated by Django 5.2.11 on 2026-02-26 16:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DIDDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Path segment in the DID URI: did:web:<host>:<org_slug>:<user>:<label>', max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SIGNED', 'Signed'), ('PUBLISHED', 'Published'), ('DEACTIVATED', 'Deactivated')], default='DRAFT', max_length=20)),
                ('content', models.JSONField(blank=True, help_text='Last published DID document JSON. Immutable once set; overwritten only on next publish.', null=True)),
                ('draft_content', models.JSONField(blank=True, help_text='Working draft. Editable by members. Becomes content on publish.', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='', help_text='Approval or rejection comment from the org admin.')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='did_documents', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Org admin who approved or rejected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Member who submitted for review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'did_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DIDDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.JSONField(help_text='Full DID document JSON at the time of publish.')),
                ('signature', models.TextField(blank=True, default='', help_text='JWS or proof block from SignServer.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('registrar_response', models.JSONField(blank=True, help_text='Response from the Universal Registrar.', null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.diddocument')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'did_document_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='diddocument',
            name='current_version',
            field=models.OneToOneField(blank=True, help_text='Points to the most recent published version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.diddocumentversion'),
        ),
        migrations.CreateModel(
            name='DocumentVerificationMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method_id_fragment', models.CharField(help_text="Fragment identifier, e.g. 'key-1'. Full ID: did:web:...:org:label#key-1", max_length=64)),
                ('method_type', models.CharField(default='JsonWebKey2020', help_text='Verification method type per DID spec.', max_length=64)),
                ('relationships', models.CharField(default='authentication,assertionMethod', help_text='Comma-separated verification relationships.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Auto-set to False when the linked certificate is revoked.')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_methods', to='certificates.certificate')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_methods', to='documents.diddocument')),
            ],
            options={
                'db_table': 'document_verification_methods',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='diddocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_version_per_document'),
        ),
        migrations.AddConstraint(
            model_name='diddocument',
            constraint=models.UniqueConstraint(fields=('organization', 'label'), name='unique_doc_label_per_org'),
        ),
        migrations.AddConstraint(
            model_name='documentverificationmethod',
            constraint=models.UniqueConstraint(fields=('document', 'method_id_fragment'), name='unique_method_fragment_per_doc'),
        ),
    ]
