# Generated by Django 5.2.11 on 2026-02-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diddocument',
            name='unique_doc_label_per_org',
        ),
        migrations.AddField(
            model_name='diddocument',
            name='owner',
            field=models.ForeignKey(default='f47ac10b-58cc-4372-a567-0e02b2c3d479', help_text='The user who created and owns this document. Appears in the DID URI as the <user> segment. Only this user can edit the document.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='created_by',
            field=models.ForeignKey(help_text='Same as owner at creation time. Kept for BaseModel consistency.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='draft_content',
            field=models.JSONField(blank=True, help_text='Working draft. Editable ONLY by the owner. Becomes content on publish.', null=True),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='The owner who submitted this document for review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentverificationmethod',
            name='method_id_fragment',
            field=models.CharField(help_text="Fragment identifier, e.g. 'key-1'. Full ID: did:web:...:org:user:label#key-1", max_length=64),
        ),
        migrations.AddConstraint(
            model_name='diddocument',
            constraint=models.UniqueConstraint(fields=('organization', 'owner', 'label'), name='unique_doc_label_per_owner_per_org'),
        ),
    ]
