# Generated by Django 6.0.3 on 2026-03-23 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_diddocument_unique_doc_label_per_org_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diddocument',
            name='content',
            field=models.JSONField(blank=True, help_text='Dernier JSON de document DID publié. Immuable une fois défini ; écrasé uniquement lors de la prochaine publication.', null=True),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='created_by',
            field=models.ForeignKey(help_text='Identique au propriétaire à la création. Conservé pour la cohérence de BaseModel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='current_version',
            field=models.OneToOneField(blank=True, help_text='Pointe vers la version publiée la plus récente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.diddocumentversion'),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='draft_content',
            field=models.JSONField(blank=True, help_text='Brouillon de travail. Modifiable UNIQUEMENT par le propriétaire. Devient contenu lors de la publication.', null=True),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='label',
            field=models.CharField(help_text="Segment de chemin dans l'URI DID : did:web:<host>:<org_slug>:<user>:<label>", max_length=120),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='owner',
            field=models.ForeignKey(help_text="L'utilisateur qui a créé et possède ce document. Apparaît dans l'URI DID comme segment <user>. Seul cet utilisateur peut modifier le document.", on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='review_comment',
            field=models.TextField(blank=True, default='', help_text="Commentaire d'approbation ou de rejet de l'administrateur de l'organisation."),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text="Administrateur de l'organisation qui a approuvé ou rejeté.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diddocument',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Soumetteur du document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diddocumentversion',
            name='content',
            field=models.JSONField(help_text='JSON complet du document DID au moment de la publication.'),
        ),
        migrations.AlterField(
            model_name='diddocumentversion',
            name='registrar_response',
            field=models.JSONField(blank=True, help_text='Réponse depuis le Universal Registrar.', null=True),
        ),
        migrations.AlterField(
            model_name='diddocumentversion',
            name='signature',
            field=models.TextField(blank=True, default='', help_text='Bloc JWS ou de preuve depuis SignServer.'),
        ),
        migrations.AlterField(
            model_name='documentverificationmethod',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Défini auto sur False quand le certificat lié est révoqué.'),
        ),
        migrations.AlterField(
            model_name='documentverificationmethod',
            name='method_id_fragment',
            field=models.CharField(help_text="Identifiant de fragment, par ex. 'key-1'. ID complet : did:web:...:org:user:label#key-1", max_length=64),
        ),
        migrations.AlterField(
            model_name='documentverificationmethod',
            name='method_type',
            field=models.CharField(default='JsonWebKey2020', help_text='Type de méthode de vérification selon la spec DID.', max_length=64),
        ),
        migrations.AlterField(
            model_name='documentverificationmethod',
            name='relationships',
            field=models.CharField(default='authentication,assertionMethod', help_text='Relations de vérification séparées par des virgules.', max_length=255),
        ),
    ]
