# Generated by Django 6.0.4 on 2026-04-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_diddocument_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diddocument',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp de la dernière relance envoyée pour ce document.', null=True),
        ),
    ]
