# Generated by Django 5.2.11 on 2026-02-26 16:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Human-friendly name, e.g. 'prod-signing-2025'.", max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='organizations.organization')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('public_key_jwk', models.JSONField(help_text='Extracted JWK representation of the public key.')),
                ('subject_dn', models.CharField(blank=True, default='', help_text="Subject DN, e.g. 'CN=example,O=Acme'.", max_length=512)),
                ('issuer_dn', models.CharField(blank=True, default='', help_text="Issuer DN, e.g. 'CN=EJBCA CA'.", max_length=512)),
                ('serial_number', models.CharField(blank=True, default='', help_text='Hex-encoded serial number.', max_length=128)),
                ('not_valid_before', models.DateTimeField(blank=True, null=True)),
                ('not_valid_after', models.DateTimeField(blank=True, null=True)),
                ('key_type', models.CharField(help_text='EC, RSA, or Ed25519.', max_length=10)),
                ('key_curve', models.CharField(blank=True, default='', help_text='P-256, P-384, etc. EC keys only.', max_length=20)),
                ('key_size', models.IntegerField(blank=True, help_text='2048, 4096, etc. RSA keys only.', null=True)),
                ('fingerprint_sha256', models.CharField(help_text='Hex SHA-256 of the DER-encoded certificate.', max_length=64)),
                ('is_current', models.BooleanField(default=True, help_text='Denormalized flag — True for the active version.')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='certificates.certificate')),
                ('certificate_file', models.ForeignKey(help_text='The uploaded PEM file.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.file')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificate_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='current_version',
            field=models.OneToOneField(blank=True, help_text='Points to the active version of this certificate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificates.certificateversion'),
        ),
        migrations.AddConstraint(
            model_name='certificateversion',
            constraint=models.UniqueConstraint(fields=('certificate', 'version_number'), name='unique_version_per_cert'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('organization', 'label'), name='unique_cert_label_per_org'),
        ),
    ]
