# Generated by Django 6.0.3 on 2026-03-23 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='current_version',
            field=models.OneToOneField(blank=True, help_text='Pointe vers la version active de ce certificat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='certificates.certificateversion'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='label',
            field=models.CharField(help_text="Nom convivial, par ex. 'prod-signature-2025'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='certificateversion',
            name='certificate_file',
            field=models.ForeignKey(help_text='Le fichier téléchargé.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.file'),
        ),
        migrations.AlterField(
            model_name='certificateversion',
            name='fingerprint_sha256',
            field=models.CharField(help_text='Empreinte SHA-256 hexa du certificat encodé DER.', max_length=64),
        ),
        migrations.AlterField(
            model_name='certificateversion',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Indicateur dénormalisé — True pour la version active.'),
        ),
        migrations.AlterField(
            model_name='certificateversion',
            name='issuer_dn',
            field=models.CharField(blank=True, default='', help_text="DN de l'émetteur, par ex. 'CN=EJBCA CA'.", max_length=512),
        ),
        migrations.AlterField(
            model_name='certificateversion',
            name='key_curve',
            field=models.CharField(blank=True, default='', help_text='P-256, P-384, etc. Pour les clés EC.', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificateversion',
            name='key_size',
            field=models.IntegerField(blank=True, help_text='2048, 4096, etc. Pour les clés RSA.', null=True),
        ),
        migrations.AlterField(
            model_name='certificateversion',
            name='key_type',
            field=models.CharField(help_text='EC, RSA, ou Ed25519.', max_length=10),
        ),
        migrations.AlterField(
            model_name='certificateversion',
            name='public_key_jwk',
            field=models.JSONField(help_text='Représentation JWK extraite de la clé publique.'),
        ),
        migrations.AlterField(
            model_name='certificateversion',
            name='serial_number',
            field=models.CharField(blank=True, default='', help_text='Numéro de série encodé en hexadécimal.', max_length=128),
        ),
        migrations.AlterField(
            model_name='certificateversion',
            name='subject_dn',
            field=models.CharField(blank=True, default='', help_text="DN du sujet, par ex. 'CN=exemple,O=Acme'.", max_length=512),
        ),
    ]
