# Generated by Django 6.0.4 on 2026-04-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_current_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateversion',
            name='extended_key_usage',
            field=models.JSONField(blank=True, help_text='Liste des OIDs (Extended Key Usage) extraite du certificat X.509.', null=True),
        ),
        migrations.AddField(
            model_name='certificateversion',
            name='key_usage',
            field=models.JSONField(blank=True, help_text='Tableau de booléens (Key Usage) extrait du certificat X.509.', null=True),
        ),
    ]
